nodeLinker: pnp
enableGlobalCache: true
enableTelemetry: false
checksumBehavior: ignore
yarnPath: .yarn/releases/yarn-4.0.2.cjs
# Plugins are resolved from local files to keep installs offline.
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-essentials.cjs
    spec: "@yarnpkg/plugin-essentials"
