import { UtensilsCrossed, Car, CreditCard, Wallet, Briefcase } from 'lucide-react';

export const TRANSACTION_TEMPLATES = [
  {
    id: 'lunch',
    mode: 'expense',
    name: 'Makan Siang',
    description: 'Pengeluaran makan siang rutin di kantor atau luar.',
    icon: UtensilsCrossed,
    advanced: false,
    preset: {
      title: 'Makan Siang',
      amount: 35000,
      category: 'Makanan',
      note: 'Makan siang kantor',
      merchant: 'Warung Favorit',
      account: 'Cash',
    },
  },
  {
    id: 'ride-hailing',
    mode: 'expense',
    name: 'Transportasi Online',
    description: 'Catatan cepat untuk ojek atau taksi online.',
    icon: Car,
    advanced: false,
    preset: {
      title: 'Transportasi Online',
      amount: 25000,
      category: 'Transportasi',
      note: 'Perjalanan ojek online',
      merchant: 'Gojek / Grab',
      account: 'Cash',
    },
  },
  {
    id: 'subscription',
    mode: 'expense',
    name: 'Langganan Streaming',
    description: 'Biaya langganan bulanan seperti Netflix atau Spotify.',
    icon: CreditCard,
    advanced: true,
    preset: {
      title: 'Langganan Streaming',
      amount: 65000,
      category: 'Langganan',
      note: 'Langganan streaming',
      merchant: 'Netflix',
      account: 'Kartu Kredit',
    },
  },
  {
    id: 'salary',
    mode: 'income',
    name: 'Gaji Bulanan',
    description: 'Pemasukan gaji tetap setiap bulan.',
    icon: Wallet,
    advanced: true,
    preset: {
      title: 'Gaji Bulanan',
      amount: 7000000,
      category: 'Gaji',
      note: 'Gaji bulan ini',
      merchant: 'Perusahaan',
      account: 'Rekening Bank',
    },
  },
  {
    id: 'freelance',
    mode: 'income',
    name: 'Proyek Freelance',
    description: 'Pendapatan dari proyek atau klien sampingan.',
    icon: Briefcase,
    advanced: false,
    preset: {
      title: 'Proyek Freelance',
      amount: 1500000,
      category: 'Lainnya',
      note: 'Bayaran freelance',
      merchant: 'Klien',
      account: 'Rekening Bank',
    },
  },
];
